name: Deploy to Firebase

on:
  push:
    branches:
      - main # Deploy when changes are pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Firebase CLI
        run: |
          npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        run: |
          firebase deploy --token $FIREBASE_TOKEN --non-interactive
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }} # Set up a secret in your GitHub repository containing your Firebase token
